### PR TITLE
Support Netconf error reporting

### PR DESCRIPTION
**Pull request by psiyengar**
Set appropriate Netconf error information when an error is encountered while processing Netconf RPC requests.

### CODE REVIEW

**Review by tony-vanderpeet — APPROVED** [review]

**Review by carlgsmith — APPROVED** [review]

**Review by carlgsmith — COMMENTED** [review]
Wait ... why are we defining netconf errors in apteryx-xml ... are these the same error codes used in restconf when using XML?

**Comment by tony-vanderpeet** [comment]
> Wait ... why are we defining netconf errors in apteryx-xml ... are these the same error codes used in restconf when using XML?

I did discuss this with Prashanth and it seems to come from the fact that there is a bit of Netconfy stuff present in apteryx-xml. I suppose setting these error structures doesn't matter if 1) the routine is only ever called from Netconf or 2) Restconf doesn't pay attention to the error in its processing (although there is possibly then going to be a memory leak in Restconf).

I will review again with this in mind and see whether I can work out which, if either, of these is true.

**Comment by tony-vanderpeet** [comment]
Yeah, all of this code is in something I wrote in apteryx-xml which is specific to Netconf. Having said that, I do have the intention to rewrite at least part of the code to use something Carl submitted at about the same time.

**Comment by tony-vanderpeet** [comment]
I think ideally we would have generic code in apteryx-xml, which creates generic error structures, which can then be interpreted by the calling protocol. However in this case, the code is specific to Netconf (only Netconf calls it) and I would suggest that if I ever refactor this code to use generic code, I will make sure that I don't put Netconf specific errors into that generic code.

**Review by tony-vanderpeet — APPROVED** [review]

**Pull request merged**
